### ISSUE TITLE
User(Licensees) feedback on prototype V1

### ISSUE THREAD

**Issue by Kghiya** [bcgov/nr-fop#49]
**Conduct user interviews and user-testing sessions, gather feedback, and prepare key insights**

**Tasks**
- [ ] Research plan (research goal, research questions, and designs)
- [ ] User interview and testing sessions
- [ ] Compile notes
- [ ] Next steps to update the design

**User Contact**
TBD as business area updates
